totalEpoch: 1000
startEpoch: 1
lr: 0.001
factor: 0.9

lossModel:
  model:
    asn:
      shape: [ 640, 640 ]
      hidden_channel: 32
    backbone:
      netID: 'b0'
      depthProb: 0.2
      useSE: True
    neck:
      data_point: [ 24, 40, 112, 1280 ]
      layer_num: 2
      exp: 256
    head:
      thresh: 0.3
      exp: 256

  loss:
    binaryLoss:
      ratio: 3.
      eps: !!float '1e-6'

score:
  totalBox: 1000
  edgeThresh: 5
  probThresh: 0.3
  scoreThresh: 0.7
  label: 'binaryMap'

accurancy:
  ignoreThresh: 0.5
  scoreThresh: 0.7
  accThresh: 0.5

train:
  batchSize: 8
  numWorkers: 2
  dropLast: True
  shuffle: True
  pinMemory: False
  dataset:
    imgType: 0
    imgDir: 'D:\workspace\project\hiertext\data1\train/image'
    tarFile: 'D:\workspace\project\hiertext\data1\train/target.json'
    prep:
      DetMask:
        ignore_thresh: 100
        erode: 11
        dilate: 11
      DetAug:
        onlyResize: False
        Fliplr:
          p: 0.5
        Affine:
          rotate: [ -20, 20 ]
          shear:
              x : [ -10, 10 ]
              y : [ -10, 10 ]
          fit_output: True
        Resize:
          size: [ 0.5, 3. ]
      DetCrop:
        minCropSize: 0.1
        maxTries: 10
        generalSize: [ 960, 960 ]
      DetNorm:
        mean: [ 122.67891434, 116.66876762, 104.00698793 ]
      DetFilter:
        key: [ 'polygon', 'ignore', 'train' ]

valid:
  batchSize: 1
  numWorkers: 4
  dropLast: True
  shuffle: True
  pinMemory: False
  dataset:
    imgType: 0
    imgDir: 'D:\TextOCR\splited\valid/image'
    tarFile: 'D:\TextOCR\splited\valid/target.json'
    prep:
      DetMask:
        ignore_thresh: 100
        erode: 11
        dilate: 11
        DetAug:
          onlyResize: True
          Fliplr:
            p: 0.5
        DetNorm:
          mean: [ 122.67891434, 116.66876762, 104.00698793 ]
        DetFilter:
          key: [ 'train' ]

optimizer:
  name: Adam
  args:
    betas: [ 0.9, 0.999 ]
    eps: !!float '1e-8'

checkpoint:
  workspace: './checkpoint'
  resume: ''

logger:
  workspace: './logger'
  level: INFO
