totalEpoch: 1000
startEpoch: 1
lr: 0.003
factor: 0.9

lossModel:
  model:
    backbone:
      netID: 'b0'
      depthProb: 0.2
      useSE: False
    neck:
      data_point: [ 24, 40, 112, 1280 ]
      exp: 256
    head:
      k: 50
      exp: 256
      adaptive: True

  loss:
    threshScale: 10
    threshLoss:
      eps: !!float '1e-6'
    probScale: 5
    probLoss:
      ratio: 3.
      eps: !!float '1e-6'
    binaryScale: 1
    binaryLoss:
      eps: !!float '1e-6'

score:
  totalBox: 1000
  edgeThresh: 5
  probThresh: 0.3
  scoreThresh: 0.7
  label: 'binaryMap'

accurancy:
  ignoreThresh: 0.5
  scoreThresh: 0.7
  accThresh: 0.5

train:
  batchSize: 1
  numWorkers: 2
  dropLast: True
  shuffle: True
  pinMemory: False
  dataset:
    imgType: 0
    imgDir: 'D:\TextOCR\splited\train/image'
    tarFile: 'D:\TextOCR\splited\train/target.json'
    prep:
      DetAug:
        onlyResize: False
        Fliplr:
          p: 0.5
        Affine:
          rotate: [ -20, 20 ]
          shear:
            x: [ -20, 20 ]
            y: [ -20, 20 ]
          fit_output: True
        Resize:
          size: [ 0.5, 3. ]
      DetCrop:
        minCropSize: 0.1
        maxTries: 10
        generalSize: [ 800, 800 ]
      DetForm:
        shrinkRatio: 0.4
      ProbMaker:
        shrinkRatio: 0.4
        minTextSize: 8
      ThreshMaker:
        expandRatio: 0.4
        minThresh: 0.3
        maxThresh: 0.7
      DetNorm:
        mean: [ 122.67891434, 116.66876762, 104.00698793 ]
      DetFilter:
        key: [ 'polygon', 'shape', 'ignore', 'train' ]

valid:
  batchSize: 1
  numWorkers: 4
  dropLast: False
  shuffle: False
  pinMemory: False
  dataset:
    imgType: 0
    imgDir: 'D:\python_project\dbpp\breg_detection\valid\image'
    tarFile: 'D:\python_project\dbpp\breg_detection\valid\target.json'
    prep:
      DetAug:
        onlyResize: True
        Resize:
          size: { "height": 960, "width": 960 }
      DetForm:
        shrinkRatio: 0.4
      ProbMaker:
        shrinkRatio: 0.4
        minTextSize: 8
      ThreshMaker:
        expandRatio: 0.4
        minThresh: 0.3
        maxThresh: 0.7
      DetNorm:
        mean: [ 122.67891434, 116.66876762, 104.00698793 ]
      DetFilter:
        key: [ 'train' ]

optimizer:
  name: Adam
  args:
    betas: [ 0.9, 0.999 ]
    eps: !!float '1e-8'

checkpoint:
  workspace: 'checkpoint'
  resume: ''

logger:
  workspace: 'logger'
  level: INFO
